from jatic_toolbox._internals.protocols import (
    ArrayLike,
    Augmentation,
    Classifier,
    HasLogits,
    HasObjectDetections,
    HasProbs,
    ImageType,
    Model,
    ModelOutput,
    NDArray,
    NestedCollection,
    ObjectDetector,
    ShapedArray,
    Tensor,
)

__all__ = [
    "NestedCollection",
    "ImageType",
    "ArrayLike",
    "NDArray",
    "Tensor",
    "Augmentation",
    "ModelOutput",
    "HasProbs",
    "HasLogits",
    "HasObjectDetections",
    "Model",
    "Classifier",
    "ObjectDetector",
    "ShapedArray",
]
